import argparse
import json
import math
import re
from collections import Counter
from pathlib import Path
from typing import Iterable

from bs4 import BeautifulSoup


TOKEN_RE = re.compile(r"[A-Za-z0-9_:+.-]+")
SENTENCE_SPLIT_RE = re.compile(r"(?<=[.!?])\s+(?=[A-Z0-9`])")
HEADING_TAGS = ("h1", "h2", "h3", "h4", "h5", "h6")
BLOCK_TAGS = HEADING_TAGS + ("p", "li", "pre", "table", "dt", "dd")
NOISE_CLASS_KEYWORDS = (
    "sphx-glr-download",
    "sphx-glr-footer",
    "sphx-glr-timing",
    "sphx-glr-script-out",
    "sphx-glr-download-link-note",
    "toctree-wrapper",
    "wy-breadcrumbs",
    "breadcrumb",
    "sidebar",
    "pagetoc",
    "toc",
)
NOISE_TEXT_PREFIXES = (
    "download jupyter notebook",
    "download python source code",
    "download zipped",
    "total running time of the script",
    "gallery generated by sphinx-gallery",
)


def normalize_whitespace(text: str) -> str:
    text = text.replace("\xa0", " ")
    text = re.sub(r"\r\n?", "\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()


def clean_inline_text(text: str) -> str:
    text = text.replace("", " ").replace("¶", " ").replace("\n", " ")
    return normalize_whitespace(text)


def normalize_code_block(text: str) -> str:
    lines = text.replace("\xa0", " ").replace("\t", "    ").splitlines()
    normalized_lines = [line.rstrip() for line in lines]
    while normalized_lines and not normalized_lines[0].strip():
        normalized_lines.pop(0)
    while normalized_lines and not normalized_lines[-1].strip():
        normalized_lines.pop()

    compacted = []
    previous_blank = False
    for line in normalized_lines:
        if not line.strip():
            if not previous_blank:
                compacted.append("")
            previous_blank = True
            continue
        compacted.append(line)
        previous_blank = False

    return "\n".join(compacted).strip()


def tokenize(text: str) -> list[str]:
    return [m.group(0).lower() for m in TOKEN_RE.finditer(text)]


def count_tokens(text: str) -> int:
    lexical_tokens = len(tokenize(text))
    whitespace_tokens = len(text.split())
    return max(1, lexical_tokens, whitespace_tokens)


def select_content_root(soup: BeautifulSoup):
    selectors = ("[role=main]", "main", "article", ".document", ".rst-content", "body")
    for selector in selectors:
        node = soup.select_one(selector)
        if node is not None:
            return node
    return soup


def prune_noise_nodes(root) -> None:
    for tag in root.find_all(["script", "style", "noscript", "svg", "nav", "header", "footer", "aside"]):
        tag.decompose()

    for node in list(root.find_all(class_=True)):
        if getattr(node, "attrs", None) is None:
            continue
        class_text = " ".join(node.get("class") or []).lower()
        if any(keyword in class_text for keyword in NOISE_CLASS_KEYWORDS):
            node.decompose()

    for node in list(root.select(".headerlink, .toc-backref")):
        node.decompose()


def extract_block_text(node) -> str:
    if node.name in HEADING_TAGS:
        text = clean_inline_text(node.get_text(" ", strip=True))
        if not text:
            return ""
        return f"{'#' * int(node.name[1])} {text}"

    if node.name == "pre":
        return normalize_code_block(node.get_text())

    separator = " | " if node.name == "table" else " "
    text = clean_inline_text(node.get_text(separator, strip=True))
    if node.name == "li" and text:
        return f"- {text}"
    return text


def is_noise_text(text: str) -> bool:
    lowered = text.lower()
    return any(lowered.startswith(prefix) for prefix in NOISE_TEXT_PREFIXES)


def html_to_blocks(html: str) -> list[dict]:
    soup = BeautifulSoup(html, "html.parser")
    root = select_content_root(soup)
    prune_noise_nodes(root)

    blocks: list[dict] = []
    for node in root.find_all(BLOCK_TAGS):
        if node.find_parent(BLOCK_TAGS):
            continue
        text = extract_block_text(node)
        if not text or is_noise_text(text):
            continue
        if blocks and blocks[-1]["text"] == text:
            continue
        blocks.append({"text": text, "is_heading": node.name in HEADING_TAGS})

    return blocks


def pack_units(units: list[str], max_tokens: int, separator: str) -> list[str]:
    packed: list[str] = []
    current: list[str] = []
    current_tokens = 0

    for unit in units:
        unit = unit.strip()
        if not unit:
            continue
        unit_tokens = count_tokens(unit)
        if unit_tokens > max_tokens:
            if current:
                packed.append(separator.join(current).strip())
                current = []
                current_tokens = 0
            packed.extend(split_large_block(unit, max_tokens))
            continue
        if current and current_tokens + unit_tokens > max_tokens:
            packed.append(separator.join(current).strip())
            current = [unit]
            current_tokens = unit_tokens
            continue
        current.append(unit)
        current_tokens += unit_tokens

    if current:
        packed.append(separator.join(current).strip())

    return [chunk for chunk in packed if chunk]


def split_large_block(text: str, max_tokens: int) -> list[str]:
    if count_tokens(text) <= max_tokens:
        return [text]

    paragraph_units = [unit.strip() for unit in re.split(r"\n{2,}", text) if unit.strip()]
    if len(paragraph_units) > 1:
        return pack_units(paragraph_units, max_tokens, "\n\n")

    line_units = [line.rstrip() for line in text.splitlines() if line.strip()]
    if len(line_units) > 1:
        return pack_units(line_units, max_tokens, "\n")

    sentence_units = [unit.strip() for unit in SENTENCE_SPLIT_RE.split(text) if unit.strip()]
    if len(sentence_units) > 1:
        return pack_units(sentence_units, max_tokens, " ")

    words = text.split()
    if not words:
        return []

    chunks = []
    for start in range(0, len(words), max_tokens):
        chunk = " ".join(words[start:start + max_tokens]).strip()
        if chunk:
            chunks.append(chunk)
    return chunks


def take_overlap(blocks: list[dict], overlap_tokens: int) -> list[dict]:
    if overlap_tokens <= 0:
        return []

    overlap: list[dict] = []
    total_tokens = 0
    for block in reversed(blocks):
        if total_tokens >= overlap_tokens:
            break
        overlap.insert(0, block)
        total_tokens += block["tokens"]

    if overlap and all(block["is_heading"] for block in overlap):
        return []
    return overlap


def chunk_blocks(blocks: list[dict], chunk_tokens: int, overlap_tokens: int) -> Iterable[str]:
    if not blocks:
        return

    expanded_blocks: list[dict] = []
    for block in blocks:
        for piece in split_large_block(block["text"], chunk_tokens):
            expanded_blocks.append(
                {
                    "text": piece,
                    "tokens": count_tokens(piece),
                    "is_heading": block["is_heading"],
                }
            )

    current_blocks: list[dict] = []
    current_tokens = 0
    heading_boundary_min_tokens = max(300, int(chunk_tokens * 0.45))

    for block in expanded_blocks:
        if block["is_heading"] and current_blocks and current_tokens >= heading_boundary_min_tokens:
            yield "\n\n".join(item["text"] for item in current_blocks).strip()
            current_blocks = []
            current_tokens = 0

        if current_blocks and current_tokens + block["tokens"] > chunk_tokens:
            yield "\n\n".join(item["text"] for item in current_blocks).strip()
            current_blocks = take_overlap(current_blocks, overlap_tokens)
            current_tokens = sum(item["tokens"] for item in current_blocks)

            while current_blocks and current_tokens + block["tokens"] > chunk_tokens:
                current_tokens -= current_blocks[0]["tokens"]
                current_blocks = current_blocks[1:]

        current_blocks.append(block)
        current_tokens += block["tokens"]

    if current_blocks:
        yield "\n\n".join(item["text"] for item in current_blocks).strip()


def build_index(chunks: list[dict]) -> dict:
    doc_tfs = []
    doc_lens = []
    df = Counter()

    for chunk in chunks:
        tokens = tokenize(chunk["text"])
        tf = Counter(tokens)
        doc_tfs.append(tf)
        doc_lens.append(sum(tf.values()))
        for term in tf:
            df[term] += 1

    num_docs = max(1, len(chunks))
    avgdl = sum(doc_lens) / num_docs if doc_lens else 0.0
    idf = {}
    for term, freq in df.items():
        idf[term] = math.log(1.0 + (num_docs - freq + 0.5) / (freq + 0.5))

    serializable_tfs = [{term: count for term, count in tf.items()} for tf in doc_tfs]
    return {
        "avgdl": avgdl,
        "doc_lens": doc_lens,
        "idf": idf,
        "doc_tfs": serializable_tfs,
        "chunks": chunks,
    }


def resolve_local_path(downloaded_manifest_path: Path, source: dict) -> Path:
    local_path = Path(source["local_path"])
    sibling_raw_path = downloaded_manifest_path.parent / "raw" / local_path.name
    if sibling_raw_path.exists():
        return sibling_raw_path
    if local_path.exists():
        return local_path

    raise FileNotFoundError(f"Could not find manual source file: {local_path}")


def build_kb(downloaded_manifest_path: Path, output_dir: Path, chunk_tokens: int, overlap_tokens: int) -> tuple[Path, Path]:
    output_dir.mkdir(parents=True, exist_ok=True)
    manifest = json.loads(downloaded_manifest_path.read_text())

    docs = []
    chunks = []

    for source in manifest["sources"]:
        local_path = resolve_local_path(downloaded_manifest_path, source)
        html = local_path.read_text(encoding="utf-8")
        blocks = html_to_blocks(html)
        text = "\n\n".join(block["text"] for block in blocks)
        docs.append(
            {
                "id": source["id"],
                "title": source.get("fetched_title") or source["title"],
                "url": source["url"],
                "category": source["category"],
                "tags": source.get("tags", []),
                "text": text,
            }
        )

        for idx, chunk in enumerate(chunk_blocks(blocks, chunk_tokens=chunk_tokens, overlap_tokens=overlap_tokens)):
            chunks.append(
                {
                    "id": f"{source['id']}::chunk::{idx}",
                    "source_id": source["id"],
                    "title": source.get("fetched_title") or source["title"],
                    "url": source["url"],
                    "category": source["category"],
                    "tags": source.get("tags", []),
                    "text": chunk,
                }
            )

    docs_path = output_dir / "docs.jsonl"
    with docs_path.open("w", encoding="utf-8") as f:
        for doc in docs:
            f.write(json.dumps(doc, ensure_ascii=False) + "\n")

    chunks_path = output_dir / "chunks.jsonl"
    with chunks_path.open("w", encoding="utf-8") as f:
        for chunk in chunks:
            f.write(json.dumps(chunk, ensure_ascii=False) + "\n")

    index = build_index(chunks)
    index_path = output_dir / "bm25_index.json"
    index_path.write_text(json.dumps(index, ensure_ascii=False), encoding="utf-8")
    return docs_path, index_path


def main() -> None:
    parser = argparse.ArgumentParser(description="Build a lightweight BM25 knowledge base from downloaded manuals.")
    parser.add_argument(
        "--downloaded-manifest",
        type=Path,
        default=Path(__file__).resolve().parent / "downloaded_manifest.json",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path(__file__).resolve().parent / "processed",
    )
    parser.add_argument("--chunk-tokens", type=int, default=1000)
    parser.add_argument("--overlap-tokens", type=int, default=160)
    args = parser.parse_args()

    docs_path, index_path = build_kb(
        args.downloaded_manifest,
        args.output_dir,
        chunk_tokens=args.chunk_tokens,
        overlap_tokens=args.overlap_tokens,
    )
    print(docs_path)
    print(index_path)


if __name__ == "__main__":
    main()
